@echo off
echo Some guidelines:
echo.
echo 1. Units are supported for numbers.
echo 2. Numbers with uncertainties are supported.
echo 3. Numpy is supported, including for numbers with uncertainties
echo 4. To import number array from excel, call from_excel(), then paste the column of numbers copied from excel, 
echo    and hit ENTER twice. Errors will be automatically generated by the function determine_uncertainty(value).
echo    If you want to import errors as well, call from_excel(True) instead.
echo 5. To export number array to excel, call to_excel(), copy the printed numbers and paste to excel.
echo 6. Use minimum(a,b) instead of min(a,b), since "min" is the unit for minute.
echo.
.\.venv\scripts\python -i .\calc.py